// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://llzoqkntqjztxyxgxwxs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxsem9xa250cWp6dHh5eGd4d3hzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3NjA2OTIsImV4cCI6MjA3MjMzNjY5Mn0.IN7qqm1opWmurQqNtCFRPn0S20pMkMoP9R3jJYVvivM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});